### ISSUE TITLE
add gamemodes command

### ISSUE THREAD

**Issue by mushis** [deurk/ktx#108]
this is a simple request.
To increase visibility of less known user modes (like hoonymode, bloodfest, even coop...) i suggest to add a `/gamemodes` command. this command would list to the user the game modes available in the server.

**Comment by tcsabina** [comment]
Started to collect these:
- race
- 1on1
- 2on2
- 3on3
- 4on4
- 10on10
- ffa
- ctf
- hoonymode
- blitz2v2 (what is this?)
- blitz4v4
- practice
- midair
- instagib
- berzerk
- lgcmode
- arena
- carena
- yawnmode (what is this?)

**Comment by tcsabina** [comment]
this is tackled with PR #164
