### ISSUE TITLE
Add XonX gamemode

### ISSUE THREAD

**Issue by mushis** [deurk/ktx#109]
`/xonx` would be like `/4on4`, except:

* /maxplayers 32
* doesn't validate number of players in teams
* doesn't validate number of teams (how about 3on3on3 guys?)
* option to allow players to join in the middle of a match (as long as they set their team to an existing one). 

**in simple words, a relaxed teammode.** 

sounds good to me!

**Comment by tcsabina** [comment]
PR #167 takes care of this

**Comment by tcsabina** [comment]
To make this work, you need to change the following setting in the server:
`set k_allowed_free_modes      4095`
