### ISSUE TITLE
SUGGESTION: Team-based Skins variables for CTF/other team modes.

### ISSUE THREAD

**Issue by OpenRift412** [deurk/ktx#120]
I feel that something that would make KTX CTF or team modes in general more polished and complete would be the addition of default team skins. For example, my friend runs a CTF server and we want to use the 3wave skins for the respective teams, but there doesn't appear to be a variable to set that server-side. It would be nice to be able to do this for the other team modes as well.

**Comment by meag** [comment]
Closing duplicate of #137
