### ISSUE TITLE
[BUG] Endgame stats bad line break

### ISSUE THREAD

**Issue by blaps** [deurk/ktx#121]
**Describe the bug**
Endgame stats looks weird with bad linebreaks.

> ciscon: yeah i had mentioned it a week ago or so, but everybody had more important things to look at heh.

> BD: it's also at the end of the game if you type 'gg' or something quickly, it won't be on a newline but rather at the end of one of those grey bars.

**To Reproduce**

1. Play a game
2. See stats output after the game

**Expected behavior**
Lines should break correctly.

**Screenshots**
![](https://cdn.discordapp.com/attachments/179895022366228481/758429882408763473/unknown.png)

![](https://media.discordapp.net/attachments/179895022366228481/757684200341110934/ezquake062.png)

**Environment:**
 - Operation System: Windows 10
 - ezQ 3.6
 - nl2.badplace.eu - last seen here, but might be everywhere.

**Additional context**
Add any other context about th

![](https://media.discordapp.net/attachments/179895022366228481/757684200341110934/ezquake062.png)
e problem here.

**Comment by deurk** [comment]
Should be fixed with c6b683cfdf2898d0deca017969ecc104f2990ad5.
Can you confirm @blaps ?

**Comment by deurk** [comment]
Seems fixed.
