### ISSUE TITLE
map change shouldn't "unready" players

### ISSUE THREAD

**Issue by mushis** [deurk/ktx#122]
related to #87 

map change shouldn't "unready" players as well.

**Comment by tcsabina** [comment]
Are we sure about this?

Should 'ready' not mean 'I am ready to play on this map'?
A possible map change maybe introduces new situations (teams are not that balanced anymore as some player might be weaker/stronger on the new map).

**Comment by blaps** [comment]
Yes, I'd like to see this, as a tool to counter idlers (oftentimes tabbed out).
If anyone would feel "unready", they can opt out with /break.

**Comment by mushis** [comment]
yea, blaps got it.

**Comment by tcsabina** [comment]
PR #154 tackles this.
