### ISSUE TITLE
[BUG] hoonymode2v2/hoonymode4v4 'broken'

### ISSUE THREAD

**Issue by meag** [deurk/ktx#126]
**Describe the bug**
Reported as broken on Discord by messia (I think)

**To Reproduce**
Unclear, no details given, just described as broken.

**Expected behavior**
Not sure what the expected behaviour was.  It's possible we should just rename the round-based modes as people may expected 'hoonymode' to be '1-life` rather than rounds-based.

**Comment by mushis** [comment]
my memory says that hoonymode was to be applied in 1on1 only, not team modes.
a quick google agreed: 
https://playmorepromode.com/guides/cpma-hoony-mode
etc
team hoony-mode is not much different from Clan Arena afaik. While CA sucks for duel, Hoonymode excels.
its a very fun gametype for duels.

i would exclude maxplayers >2 in hoonymode

**Comment by meag** [comment]
Hi mushi

You've just demonstrated "It's possible we should just rename the round-based modes as people may expected 'hoonymode' to be '1-life` rather than rounds-based."  The team-based hoonymode was always rounds-based & the spawns were swapped, but never one-life (which is just clan arena), you could always respawn and every frag counts.

It's called blitz in the latest version so hopefully we'll see less confusion in future.

Thanks,

**Comment by meag** [comment]
Closing this as no-one has reported concrete problems, so suspect it is just confusion over the name.
Have played multiple matches vs the bots locally and no bugs have visibly shown up.
