### ISSUE TITLE
Elected admin tweaks

### ISSUE THREAD

**Issue by HangTimeQW** [deurk/ktx#127]
There are a couple of tweaks I would like applied to elected admin behaviour.

1) Force confirmation of /break command issues by elected admins to avoid situations where a player forgets they have admin, votes for break and instantly ends the match even if nobody else has voted.  This happens typically in mix games where an admin is elected in prewar to forcestart and remove idlers. 

2) Don't automatically 'inherit' map change votes cast prior to a player being elected admin.  E. G. If a player votes for dm2, then is elected admin the map currently will instantly change to dm2 even if nobody has voted for it since the player was elected admin.

3) Exclude players marked as AFK from the voting threshold calculation.  This avoids a paradox situation where people are idle and need to be prompted by forcestart but because they are idle you can't get an admin elected in order to do this.

**Comment by mushis** [comment]
My opinion. 
1. Yeah. A suggestion is that an admin must vote twice the same thing. For example, to break, he would /break, and receive a message "repeat the command to enforce admin command". Until then, it would count as a regular player vote.
2. Yeah, this one is obvious.
3. If there's a malicious player, he could wait until everyone is afk to be an admin :) may need some more control on this one. But yeah, something like this would be cool

**Comment by meag** [comment]
"A suggestion is that an admin must vote twice the same thing" ... so how would they cancel their original /break?

Can we automatically demote elected admins when the match starts?

**Comment by HangTimeQW** [comment]
Probably OK, it's very rare that elected admin privileges are actually
needed once a match starts.

**Comment by mushis** [comment]
> "A suggestion is that an admin must vote twice the same thing" ... so how would they cancel their original /break?

I see. how about this? if the player is admin, the vote is cast normally, but adding "type yes in the console to enforce last command as admin". something like that. if the admin doesn't type yes, they could cancel their vote.

**Comment by tcsabina** [comment]
About 1) of the original post:
I don't see that a 'break' from an elected admin immediately ends the game. Is this for sure? I am testing with 1on1 on my local setup, but the 'break' from the elected admin only counts as one break, and not stopping the game.
Is this different with 2on2, 4on4?

About 3):
I kind of agree with mushi. This could be miss used...
I don't see a good solution...

**Comment by HangTimeQW** [comment]
When I wrote this request an elected adminended the game (unintentionally) immediately with /break on multiple occaisions so unless the code has changed since, that's how it works.

**Comment by tcsabina** [comment]
hmm, okay....

@meag ,
I see that you have tackled item 2) in your fork. Are you planning to merge it back anytime soon, with those other additions that you have made in the past months?

**Comment by tcsabina** [comment]
The 2 changes @meag have made in his fork are part of PR #153. This is tackling item 2).
Item 1) yet to be verified.
Item 3) will not be implemented, as that is not that trivial.

**Comment by tcsabina** [comment]
Issue reopened, as the implemented solution (to revoke the admin rights upon match start) is not a good solution.
It needs to be reverted, so and elected admin stays and admin upon match start, and a new feature shall be added:
- if an elected admin votes a map, his vote is just an ordinary vote (not a forced map change)
- give the possibility to the elected admin to force a map change (forcemap <mapname>)

**Comment by tcsabina** [comment]
PR #160 reverts the changes that made elected admins losing admin rights upon match start
