### ISSUE TITLE
[BUG] Current meson build for windows x86 crashes on map with bot support

### ISSUE THREAD

**Issue by meag** [deurk/ktx#131]
**Describe the bug**
Server hangs when trying to use bots

**To Reproduce**
Compile with bot support enabled, without `-msse2 -mfpmath=sse` compiler flags for windows-x86
Run using mvdsv, select map with bot support and enable bots.

**Solution**
`-msse2 -mfpmath=sse` - add to `c_args`, current setup of meson files & cross-compilation etc is too advanced for me to get this working with my knowledge of meson which at this stage covers "what to do when you've added another source file"

I've been handing out self-compiled versions as fixes on discord, which have been working because they're built in MSVC, and these settings are the default (64-bit version shouldn't have this problem either but I haven't tested)

**Comment by meag** [comment]
@fzwoch help! :)

**Comment by fzwoch** [comment]
Would that affect otherx 32 bit builds as well?

**Comment by meag** [comment]
Hmmm - I think this affects all 32bit builds.  Hasn't been reported on Linux but probably because there's no-one using it
