### ISSUE TITLE
[REQ] Improved /pause

### ISSUE THREAD

**Issue by blaps** [deurk/ktx#138]
**Describe the request**
Currently, only elected admins can `pause `the game forcing players to `elect` an admin before official games which is something that rarely happens and is often forgotten. In the past, votepause has been suggested which is flawed by the fact that the opposing team needs to agree to the pause before the game reaches stoppage of play, costing valuable seconds.

**Suggestion/solution**
If a game has a `matchtag` set, which has become common practice for official games, allow any of the players in the game (not spectators) to type `pause` and the game is immediately paused. The reason why this is a favorable approach is because a pause can happen immediately in the event of a disconnect/crash/other emergency. It doesn't affect normal practice games/mix games as they tend to not use the `matchtag` feature. In a tournament setting, abuse would easily be spotted and reported and action can be made against the abusing player.
Perhaps each player should be given 3 `pause` per match, which can be communicated in console.
Also, servers should [automatically `pause` when a player drops](https://github.com/deurk/ktx/issues/113). 

**Summary**
If matchtag is set, allow immediate pauses from all players.

**Comment by tcsabina** [comment]
@deurk,

This is implemented with PR #142. Can you please merge?

Toma

**Comment by tcsabina** [comment]
Available from KTX V1.40.

I think we can close this.
