### ISSUE TITLE
LG EndGame Stats

### ISSUE THREAD

**Issue by dracsqw** [deurk/ktx#170]
EndGame KTX stats of DM3 need to have LG's TOOK, KILLED, DROPPED just the same as rocket. Long overdue - and hopefully can be done rather than waiting for the "entire stats overhaul" thing and added in because it's a critical stat!

**Comment by tcsabina** [comment]
Updated title, as this is not only for DM3, but for every map with LG

**Comment by tcsabina** [comment]
It's coming, dracs ;)
![image](https://user-images.githubusercontent.com/17887592/133162010-9e48ce6b-468b-44ad-a43b-5c426b61d393.png)
![image](https://user-images.githubusercontent.com/17887592/133162085-697dc6de-eb18-4047-80f8-4424c5f32ab2.png)

**Comment by tcsabina** [comment]
PR #180 takes care of this

**Comment by dracsqw** [comment]
Yeah baby! Now everyone needs to update their servers eh
