### ISSUE TITLE
hide episode maps from /maps list

### ISSUE THREAD

**Issue by mushis** [deurk/ktx#27]
Should be possible to toggle the display of episode maps when issuing /maps

http://upload.foppa.dk/files/ezquake053.png

Listing Episode maps takes lots of space and may confuse players. Also the text description should be printed on end, and not on the beginning of the maps lists.

**Comment by mushis** [comment]
@jite

**Comment by deurk** [comment]
IMO, `/maps/` should display available maps, period. If episode maps are part of the available ones, they should be displayed.

**Comment by blaps** [comment]
Sure. But as @mushis also suggested description should really be printed on end.
