### ISSUE TITLE
FFA: matchless mode for all gametypes

### ISSUE THREAD

**Issue by mushis** [deurk/ktx#4]
k_matchless forces mode to ffa
k_mode seems to do nothing

it should allow ctf or teamplay modes, even instagib, arena, clanarena, etc.

I want to setup a matchless ktx ctf server, matchless teamplay.

some related info here: http://www.quakeworld.nu/forum/topic/5538/matchless-ktx-with-ctf-1on1-arena#65935

**Comment by deurk** [comment]
Damn, that issue is old, but the link is a 2011 necro-link! ☠️

Should we spend time on this or was the use case very specific?

**Comment by mushis** [comment]
blood dog implemented match CTF a couple of years ago.

**Comment by deurk** [comment]
Then let's close this issue. Thanks @mushis.
