### ISSUE TITLE
CTF: /tossrune

### ISSUE THREAD

**Issue by meag** [deurk/ktx#42]
Reported by Blood Dog on Discord.

```this is a relatively minor issue, but if you're in ctf mode and pickup a rune then tossrune to throw it, it throws at a weird angle (does some kind of spin in the air) and then often falls halfway into the ground, instead of landing cleanly on top of the ground```

**Comment by mushis** [comment]
reproduced at work pc with vanilla nquake.
couldn't reproduce at home pc with nightly build ezq

**Comment by meag** [comment]
Right, this is really for nquake to fix... ezquake will render the models upright if they are .mdl files (id1/pak1.pak) with the EF_ROTATE flag set.  If it finds a .md3, it reads the flags from the .mdl file.

In the nquake models.pk3 file there are md3 files named .mdl, so ezquake can't read the original .mdl files to get the flags, so it's just a freely-rotating entity.  Did someone deliberately call these .md3 files .mdl in order to stop ezquake keeping them upright?

maybe just disable rotation server-side (as blood dog suggested on discord) as the rotation should be ignored anyway?
