### ISSUE TITLE
Download page not working

### ISSUE THREAD

**Issue by javian** [deurk/ktx#47]
It seems that builds.deurk.net which is linked to in the readme no longer works.

**Comment by ciscon** [comment]
might i suggest we start pushing the jenkins builds to qw.nu for nightlies?

**Comment by deurk** [comment]
I'll restore the domain, I cleaned DNS zones and forgot this one was used.

**Comment by deurk** [comment]
Will keep it open until it is actually solved to not forget mid-resolve :)
