### ISSUE TITLE
BOTS: Crash when trying to enable bots on 32bit mvdsv/ktx

### ISSUE THREAD

**Issue by liback** [deurk/ktx#49]
I'm on a 64-bit system and built 32-bit binaries with bot support using meson which seem to work until i do a botcmd enable, then it crashes ("MVDSV not responding"). Can see a map reload initiated but i never enter the server.

**Comment by deurk** [comment]
Is this still an issue ?

**Comment by meag** [comment]
We resolved this on Discord, the issue was with the .dll in the automated builds.
