### ISSUE TITLE
REQ: Race route for monsoon

### ISSUE THREAD

**Issue by meag** [deurk/ktx#53]
[20:28] VVD: @meag, can u add, plz, race for monsoon: start at YA, finish at RA, weapons allowed
[20:29] VVD: did it for ~3.2s

**Comment by VVD** [comment]
monsoon not bravado :-D

**Comment by VVD** [comment]
[monsoon.route.txt](https://github.com/deurk/ktx/files/3193256/monsoon.route.txt)

**Comment by VVD** [comment]
Updated version of [monsoon.route](https://github.com/deurk/ktx/files/3274017/monsoon.route.txt).
