### ISSUE TITLE
ISSUE: Make sure /rpickup always changes at least 1 player

### ISSUE THREAD

**Issue by meag** [deurk/ktx#54]
[23:30] Kernell: @meag   when will we (and by We I mean You) fix the damn /RPICKUP command :joy: 
seriously 2019 it's still shit

just put an IF to test if the teams remains the same,   then    Auto-Rpick  again until it changes
[23:31] Kernell: it stays ALWAYS the same teams 3 times  (we have to issue  /rpickup  3 times every-time)

**Comment by wernerml** [comment]
YESSSSSS   =D

**Comment by mushis** [comment]
do it will not be random anymore??

joking, this makes sense:)

**Comment by wernerml** [comment]
any update?

**Comment by wernerml** [comment]
:D

**Comment by mushis** [comment]
i'm unsure of the "fix" - it apparently just says in the console that the teams haven't changed, and a new pickup should be voted. really? /rpickup again?? this doesn't fix the issue. read issue's title.

imo it should do rpickups automatically until the teams change.
