### ISSUE TITLE
CTF: Adjust runes power

### ISSUE THREAD

**Issue by fernandosalvatori** [deurk/ktx#64]
Hello friends,

We are a community of 50 CTF players in Brazil and would like to request an adjustment in the CTF module:

Based on CRCTF version 3.2 or higher, do the runes have a lower power than the current, could you set the power of the Strenght and Resistence Runes to 1.5 instead of 2.0?

This will allow us to get a fair CTF similar to the quakeone.com MOD

Our servers:

jaula.quakeworld.com.br port 28502
quake1.servequake.com port 28501

Thanks in advance and greetings from friends from Brazil.
Fernando Salvatori (Droni)

**Comment by mushis** [comment]
oi,
I agree that those runes (at least strength) are too powerful for today's standards.

Please, open more issues to improve KTX CTF, i think you're the only ones playing it.

**Comment by fernandosalvatori** [comment]
Dear,

I opened the combat.c program, made the adjustments, and made a new version of qwprogs.so provisionally, however, we would very much like the change of powers to come officially and committed on GITHUB.

Our WhatsApp group has 50 active CTF players, and every night we are active and playing at least 4 vs 4 CTF matches, if you want to keep up, we are at the addresses posted above.

Our Facebook group: https://www.facebook.com/groups/182158788567859/?ref=bookmarks

Thank you all.

**Comment by fernandosalvatori** [comment]
Recent game in 12/27.2019 :-)

https://ibb.co/MDbvvrd

**Comment by fernandosalvatori** [comment]
Recent game in 12/27/2019 :-)

(Secure Link, only screenshot - I am Droni)

https://ibb.co/MDbvvrd
https://ibb.co/Ky6HV9j

Recent gaming (01/02/2019 - 3am gmt -3)

https://ibb.co/JQN5ddc

**Comment by fernandosalvatori** [comment]
Dear,

I opened the combat.c program, made the adjustments, and made a new version of qwprogs.so provisionally, however, we would very much like the change of powers to come officially and committed on GITHUB.

To support, open the combat.c program, change the lines ([damage *= 2] to [damage *= 1.5] to strength, to resistence change [damage /= 2] to [damage /= 1.5]).
Rune powers cannot be similar to quad or red armor, they are only supports (The Regeneration and haste runes are perfect.)

Our WhatsApp group has 50 active CTF players, and every night we are active and playing at least 4 vs 4 CTF matches, if you want to keep up, we are at the addresses posted above.

Our Facebook group: https://www.facebook.com/groups/182158788567859/?ref=bookmarks

Thank you all.

**Comment by mushis** [comment]
acabei de fazer isso :)
aparece no http://discord.quake.world

**Comment by deurk** [comment]
It is now pushed into master.

**Comment by deurk** [comment]
A comment was made:

> I have an issue with this, the CTF runes have been that way for 20+ years, and just recently the brazilians started to play it and felt they were overpowered so wanted to reduce the benefit of strength and resistance runes from 2x to 1.5x each.

This always has been the issue with ktx changes : do we change or do we not. My answer over the years have usually been "make it a variable with a default value of what's it's always been" and I will revert the change made here and go that direction instead.

**Comment by deurk** [comment]
@fernandosalvatori @mushis Want to give the ctf_runes_options a run to see if it works like intended?

**Comment by mushis** [comment]
already tried, didn't work.

**Comment by mushis** [comment]
ok now it works.
STR: OK
RES: OK
HST: NOTOK - doesn't change the player's speed
RGN: OK, recovers Health quicker

i'de say HST and RGN doesn't make sense to change, can be removed.

**Comment by deurk** [comment]
OK. Will have another look.
I want to keep haste and regeneration, since they can be configured separately.

**Comment by deurk** [comment]
I don't see any issue with the haste rune. Player does not run faster, but it never has afaik. Tested with build 1.38, straight player speed is always capped at 320. Weapons are available faster with the hast rune though, as they should be.

I will close the issue with the merge if there aren't any other issues.

**Comment by mushis** [comment]
a player with haste i think it runs at 400 ups.
definitely faster than 320
if he is not moving faster, then its a bug

**Comment by deurk** [comment]
OK, client config was my issue: cl_maxspeed should NOT be set to 320 if you want to go faster with haste rune :D
