### ISSUE TITLE
rpickup command shouldn't "unready" players

### ISSUE THREAD

**Issue by mushis** [deurk/ktx#87]
if a player types /ready, it means they're ready to play
but if a random pickup vote passes, everyone becomes "not ready". why is this? 
the player is ready to play. if he doesn't agree with the teams, just /break

it happened to me once or twice: i readied up, went to windows, and when i came back, ppl were waiting for me to ready up! i just wanted to start the game, and i ended up delaying it. without intention.

rpickup command shouldn't "unready" players

**Comment by mr0wnage** [comment]
Agree!

**Comment by mushis** [comment]
@deurk how about in map change?
that could work too :)
