### ISSUE TITLE
I tried everything and cant play with (add) bots

### ISSUE THREAD

**Issue by ptrb78** [deurk/ktx#94]
I have compiled both ktx and mvdsv from source. Both work but i cant add bots into game. Im sure my ktx build works and is compiled with bots. After proper command (botcmd addbot) nothing happens (no bot in game) just list of bot commands. Could you tell me what am i doing wrong?

**Comment by meag** [comment]
Hi

What client are you using?

Thanks,
meag

**Comment by ptrb78** [comment]
Darkplaces quake client.

**Comment by ptrb78** [comment]
Sorry its my QW client issue. ezQuake works with bots. Closing.
